export {default as Home } from './Home'
export {default as Header } from './Header'
export {default as Skills } from './Skills'
export {default as Project } from './Project'
export {default as About } from './About'
export {default as Contact } from './Contact'
export {default as Wallet } from './Wallet'
export {default as Footer } from './Footer'
